name: Dwaynefortierphotography.com
favicon: null
layout_spectrum: 0.23289
typography_spectrum: 1
title: Dwayne Fortier Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eeebe6'
    - '#361f08'
    - '#c4bdb5'
    - '#6f451f'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
