title: Dwayne Fortier Photography
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6090226
  brandStrength: 0.5
  lightness: 0.6466165
  brandColors:
    - '#000000'
    - '#eeebe6'
    - '#361f08'
    - '#c4bdb5'
    - '#6f451f'
  rhythmicContrast: 0.2017544
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Dwaynefortierphotography.com
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8416443
layout_spectrum: 0
