layout_spectrum: 0.2368421
typography_spectrum: 0.8416443
color:
  saturation: 0.6246867
  brandStrength: 0.8037261
  lightness: 0.6466165
  rhythmicContrast: 0.4241855
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Dwaynefortierphotography.com
