name: Dwaynefortierphotography.com
favicon: null
layout_spectrum: 0.25626
typography_spectrum: 0.8416443
title: Dwayne Fortier Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#303030'
    - '#747474'
    - '#c2c2c2'
    - '#f2f2f2'
  brandStrength: 0.625
  lightness: 0.6466165
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
